# fly.toml app configuration file generated for docker-posthog-proxy on 2025-06-02T12:45:33+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app            = 'docker-posthog-proxy'
primary_region = 'fra'

[build]

[http_service]
  internal_port        = 80
  force_https          = true
  auto_stop_machines   = 'stop'
  auto_start_machines  = true
  min_machines_running = 1
  max_machines_running = 1
  processes            = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[env]
  YOUR_TRACKING_DOMAIN = "flye.codemonument.com"
